### ISSUE TITLE
 bareos.job.py get_total_jobs is broken

### ISSUE THREAD

**Issue by lexa500** [IvanBayan/Zabbix-bareos#1]
This leads to an error trigger (Can't fetch data from bareos DB), because of get_total_jobs outputs 0
Fix:
on line 38 replace['count'] with ['count(job)']

**Comment by IvanBayan** [comment]
Hello, I'm on it.
Sorry for delay, I need to setup bareos environment first.

**Comment by IvanBayan** [comment]
@podjad3k is faster than me. :)
Fixed in 5816ad630b60817c17779c2bd3647c5cb5ed3172
